### ISSUE TITLE
App Crash when presenting PayFort controller

### ISSUE THREAD

**Issue by hamza-faroooq** [payfort/fort-ios-sdk#6]
- Unknown class PFKJVFloatLabeledTextField in Interface Builder file.

- -[UITextField setFloatingLabelActiveTextColor : ] : unrecognized selector sent to instance 0x124800000

- *** Terminating app due to uncaught exception 

Please help

**Comment by PayFortIntegration** [comment]
Hello Hamza,

Please contact us directly on integration-ps@amazon.com in order to assist you better. 


Best Regards

**Comment by hamza-faroooq** [comment]
I have resolved the issue by doing the following step:

> Set -ObjC in the Other Linker Flags in the Target -> Build Settings Tab

As I have downloaded the latest version of Xcode 12.4, -ObjC tag somehow got deleted from there. So I have to add it again.

**NOTE**: Their support team does not help at all. I have to find the issue myself. Thank you for nothing. :-)
